config/routes.rb
require 'versionist/routing_params.rb'

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :employees do
    member do
      match :related_to_department, to: 'employees#related_to_department', as: 'related_to_department', via: %i(get)
    end
  end

  resources :departments do
    member do
      match :connect_employee, to: 'departments#connect_employee', as: 'connect_employee', via: %i(get patch)
      match :connect_employees, via: %i(get post)
    end
  end
  # resources :users, only: %I[profile]

  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations' }


  ### API ###
  namespace :api, defaults: { format: :json } do
    api_version(api_version_params(1, defaults: { format: :json }, default: true)) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end

    end

    api_version(api_version_params(2, defaults: { format: :json })) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end
    end

  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :departments_employees, dependent: :destroy
  has_and_belongs_to_many :departments, -> { distinct }, through: :departments_employees
  has_one :profile
  validates :email, presence: true, length: { maximum: 64 }
  validates :email, uniqueness: true
  validates_format_of :email, with: /@/, length: { maximum: 128 }

  accepts_nested_attributes_for :profile
end

app/controllers/api/employees_controller.rb
module Api
  class EmployeesController < Api::BaseController
    before_action :load_employees, only: :index
    before_action :current_object, only: %i[show update destroy]
    attr_accessor :employees, :current_object

    before_action :authenticate_user!, except: %I[index]

    def default_serializer_options
      { serializer: namespace_for_serializer::EmployeeSerializer }
    end

    def index
      respond_with employees, meta: pagination_meta(employees).merge!(links: pagination_links(employees, sort: params[:sort])), adapter: :json
    end

    def create
      result = EmployeeInteractors::Create.call(employee_params: employee_params, profile_params: profile_params)
        if result.employee.errors.present? || result.employee.profile.errors.present?
          data = {}
          data[:employee] = result.employee.errors.full_messages if result.employee.errors.present?
          data[:profile] = result.employee.profile.errors.full_messages if result.employee.profile.errors.present?
          render json: data, status: :unprocessable_entity
        else
          respond_with result.employee, status: :created
        end
    end

    def update
      result = EmployeeInteractors::Update.call(current_object: current_object, employee_params: employee_params, profile_params: profile_params)
      if result.employee.errors.present? || result.employee.profile.errors.present?
        data = {}
        data[:employee] = result.employee.errors.full_messages if result.employee.errors.present?
        data[:profile] = result.employee.profile.errors.full_messages if result.employee.profile.errors.present?
        render json: data, status: :unprocessable_entity
      else
        render json: result.employee, status: :ok
      end
    end

    def show
      super
    end

    def destroy
      super
    end

    private

    def employee_params
      params.require(:employee).permit(:id, :vacation, :status, :email)
    end

    def profile_params
      return unless params.require(:employee)[:profile].present?
      params.require(:employee)[:profile].permit(
          :id, :first_name, :last_name, :second_name, :gender, :date_birth,
          :phone_number, :time_zone, :avatar,
          working_hours: [
            { sunday: %I[from to] },
            { monday: %I[from to] },
            { tuesday: %I[from to] },
            { wednesday: %I[from to] },
            { thursday: %I[from to] },
            { friday: %I[from to] },
            { saturday: %I[from to] }
          ]
      )
    end

    def current_object
      @current_object = Employee.find(params[:id])
    end
    
    def order_by(order_by)
      super
      if order_by && order_by.blank? || order_by.nil? || order_by == '-'
        "profiles.first_name"
      else
        order_by[0] == '-' ? "profiles.#{order_by[1..-1]}" : "profiles.#{order_by}"
      end
    end

    def load_employees
      @employees ||=
        Employee.eager_load(:profile)
          .paginate(page: params[:page], per_page: params[:per_page] || Api::BaseController::PER_PAGE)
          .order(sort_params(params[:sort]))
    end

    protected

      def pagination_links(data_object, sort:)
        {
          current_page: '',
          first_page: '',
          next_page: '',
          prev_page: '',
          last_page: ''
        }
      end

  end
end

app/controllers/api/v1/employees_controller.rb
module Api
  module V1
    class EmployeesController < Api::EmployeesController
      def pagination_links(data_object, sort:)
        super
        list = {}
        list[:current_page] = api_v1_employees_url(page: data_object.current_page, sort: sort)
        list[:first_page] = api_v1_employees_url(page: 1, sort: sort) unless data_object.current_page == 1
        list[:prev_page] = api_v1_employees_url(page: data_object.previous_page, sort: sort) unless data_object.previous_page.nil?
        list[:next_page] = api_v1_employees_url(page: data_object.next_page, sort: sort) unless data_object.next_page.nil?
        list[:last_page] = api_v1_employees_url(page: data_object.total_pages, sort: sort) unless data_object.total_pages == data_object.next_page
        list
      end
    end
  end
end

app/controllers/api/v2/employees_controller.rb
module Api
  module V2
    class EmployeesController < Api::EmployeesController
      def pagination_links(data_object, sort:)
        super
        list = {}
        list[:current_page] = api_v2_employees_url(page: data_object.current_page, sort: sort)
        list[:prev_page] = api_v2_employees_url(page: data_object.previous_page, sort: sort) unless data_object.previous_page.nil?
        list[:next_page] = api_v2_employees_url(page: data_object.next_page, sort: sort) unless data_object.next_page.nil?
        list
      end
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!, except: %I[index]

  before_action :current_employee, only: %I[new create show update edit destroy related_to_department]

  before_action :departments, only: %I[related_to_department]
  before_action :department, only: %I[related_to_department]
  before_action :employees, only: %I[index]

  respond_to :html, :json, :js

  attr_reader :department, :employee

  def index; end

  def new
    @employee = Employee.new
    @employee.build_profile
  end

  def create
    Employee.transaction do
      @employee = Employee.new employee_params
      Profile.transaction do
        @profile = @employee.build_profile profile_params
        if @employee.valid? && @profile.valid? && @employee.save!
          redirect_to employees_path, notice: 'Employee create!'
        else
          render :new
        end
      end
    end
  end

  def edit; end

  def update
    Employee.transaction do
      Profile.transaction do
        if current_employee.update_attributes(employee_params) && current_employee.profile.update_attributes(profile_params)
          redirect_to employees_path, notice: 'Employee update!'
        else
          render :edit
        end
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
      format.js
    end
  end

  def related_to_department
    if !department.blank? && params[:connected] == 'true'
      employee.departments << department
    elsif !department.blank? && params[:connected] == 'false'
      employee.departments.delete(department)
    end
  end

  private

  def employee_params
    params.require(:employee).permit(:id, :vacation, :status, :email)
  end

  def profile_params
    return unless params.require(:employee)[:profile_attributes].present?
    params.require(:employee)[:profile_attributes].permit(
      :id, :first_name, :last_name, :second_name, :gender, :date_birth,
      :phone_number, :time_zone, :avatar,
      working_hours: [
        { sunday: %I[from to] },
        { monday: %I[from to] },
        { tuesday: %I[from to] },
        { wednesday: %I[from to] },
        { thursday: %I[from to] },
        { friday: %I[from to] },
        { saturday: %I[from to] }
      ])
  end

  def current_employee
    @employee ||= Employee.find(params[:id]) if params[:id]
  end

  def department
    @department ||= Department.where(id: params[:department_id])
  end

  def departments
    @departments ||= Department.select(:id, :name)
  end

  def employees
    @employees ||=
      Employee.eager_load(:profile)
        .paginate(page: params[:page], per_page: params[:per_page] || ApplicationController::PER_PAGE)
        .order(sort_params(params[:sort]))
  end

  def order_by(order_by)
    super
    if order_by && order_by.blank? || order_by.nil? || order_by == '-'
      'profiles.first_name'
    else
      order_by[0] == '-' ? "profiles.#{order_by[1..-1]}" : "profiles.#{order_by}"
    end
  end
end

app/views/employees/_block_btn.html.slim
- count_departments = employee.departments.pluck(:name).count
.pull-right
  - if employee
    - if policy(employee).view_department?
      = link_to related_to_department_employee_path(employee), class: 'btn btn-default departments related_to_departments', title: "#{employee.departments.map(&:name).join(', ')}", data: {remote: true} do
        i.fa.fa-connectdevelop aria-hidden="true"
        span class="btn btn-circle btn-info" = count_departments
    - if policy(employee).update?
      = link_to edit_employee_path(employee), class: 'btn btn-primary' do
        i.fa.fa-pencil
    - if policy(employee).destroy?
      = link_to employee_path(employee), class: 'btn btn-danger', method: :delete, data: {remote: true, confirm: 'Are you sure?'} do
        i.fa.fa-trash

app/views/employees/_departments.html.slim
.modal.fade id="departmentsModal" aria-hidden="true" aria-labelledby="departmentsModal" role="dialog"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" ×
        h4.modal-title#departments_title
          = "Departments:"
      .modal-body
        #employee_info
        #departments-ModalBody

app/views/employees/_form.html.slim
.panel-body
  = form_for employee, url: action_path,  html: { class: 'form-horizontal', role: 'form' } do |f|
    .form-group.field class="#{employee.errors.include?(:email) ? 'has-error' : ''}"
      = f.label :email, 'Email'
      = f.text_field :email, class: 'form-control'
      = error_message_for :email, employee
    .form-group.field class="#{employee.errors.include?(:in_vocation) ? 'has-error' : ''}"
      = f.label :in_vocation, 'IN vocation'
      br
      = f.radio_button :in_vocation, 'TRUE', checked: employee.in_vocation ? true : false
      | TRUE
      = f.radio_button :in_vocation, 'FALSE', checked: !employee.in_vocation ? true : false
      | FALSE
      = error_message_for :in_vocation, employee

    = f.fields_for :profile do |profile_attr|
      .form-group.field class="#{employee.profile.errors.include?(:first_name) ? 'has-error' : ''}"
        = profile_attr.label :first_name, 'First Name'
        = profile_attr.text_field :first_name, class: 'form-control'
        = error_message_for :first_name, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:last_name) ? 'has-error' : ''}"
        = profile_attr.label :last_name, 'Last Name'
        = profile_attr.text_field :last_name, class: 'form-control'
        = error_message_for :last_name, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:second_name) ? 'has-error' : ''}"
        = profile_attr.label :second_name, 'Second Name'
        = profile_attr.text_field :second_name, class: 'form-control'
        = error_message_for :second_name, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:phone_number) ? 'has-error' : ''}"
        = profile_attr.label :phone_number, 'Phone'
        = profile_attr.text_field :phone_number, class: 'form-control'
        = error_message_for :phone_number, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:gender) ? 'has-error' : ''}"
        = profile_attr.label :gender, 'gender'
        br
        = profile_attr.radio_button :gender, 'male', checked: true
        | Male
        = profile_attr.radio_button :gender, 'female'
        | Female
        = error_message_for :gender, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:date_birth) ? 'has-error' : ''}"
        = profile_attr.label :date_birth, 'Birth date'
        .input-group.date.date_picker
          = profile_attr.text_field :date_birth, class: "form-control #{employee.profile.errors.include?(:date_birth) ? 'has-error' : ''}"
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
        - if employee.profile.errors.include? :date_birth
          = error_message_for :date_birth, employee.profile
      .form-group.field class="#{employee.profile.errors.include?(:avatar) ? 'has-error' : ''}"
        = profile_attr.label :avatar
        = profile_attr.file_field :avatar, class: "form-control #{employee.profile.errors.include?(:avatar) ? 'has-error' : ''}"
        - unless employee.profile.avatar.blank?
          = image_tag employee.profile.avatar.url(:thumb)
      .form-group.field
        h3.with-line-top Working Hours
        = profile_attr.fields_for :working_hours do |working_hours|
          - Date::DAYNAMES.each do |day|
            = working_hours.fields_for day.downcase do |builder|
              .form-group class="#{employee.profile.errors.include?("working_hours_#{day.downcase}".to_sym) ? 'has-error' : ''}"
                .row
                  = builder.label :from, day, class: 'col-lg-2 col-md-2 control-label'
                  - from = profile_attr.object.working_hours_field(day.downcase.to_sym, :from).kind_of?(Time) ? profile_attr.object.working_hours_field(day.downcase.to_sym, :from).in_time_zone.strftime(t('time.formats.time')) : profile_attr.object.working_hours_field(day.downcase.to_sym, :from)
                  - to = profile_attr.object.working_hours_field(day.downcase.to_sym, :to).kind_of?(Time) ? profile_attr.object.working_hours_field(day.downcase.to_sym, :to).in_time_zone.strftime(t('time.formats.time')) : profile_attr.object.working_hours_field(day.downcase.to_sym, :to)
                  .col-lg-5.timepicker-range
                    .input-group.date.time_picker
                      .input-group-addon From
                      span.input.from= builder.text_field :from, class: 'form-control col-lg-2 col-md-2 time-picker btn', value: from
                      i.fa.fa-clock-o aria-hidden="true"
                  .col-lg-4.timepicker-range
                    .input-group.date.time_picker
                      .input-group-addon To
                      span.input.from= builder.text_field :to, class: 'form-control col-lg-2 col-md-2 time-picker btn', value: to
                      i.fa.fa-clock-o aria-hidden="true"
                .row
                  = error_message_for "working_hours_#{day.downcase}".to_sym, employee.profile
    .form-group
      = f.submit action_name == 'edit' ? 'Update' : 'Create', class: 'form-control btn btn-primary submit-button'

app/views/employees/_info.html.slim
h5
  | Employee:
  strong
    = employee.email
    |
    = employee.profile.full_name

app/views/employees/_lhs_table_users.html.slim
- if employees
  table class="table table-hover table-inbox"
    tr
      th Avatar
      th Full Name
      th Email
      th Gender
      th Date Birth
      - if controller_name == 'employees'
        th
      - employees.each do |employee|
        tr data-id=employee.id
          th
            - unless employee.profile.avatar.blank?
              = image_tag employee.profile.avatar.url(:thumb)
          td= "#{employee.profile.first_name} #{employee.profile.last_name}"
          td= employee.email
          td= employee.profile.gender
          td= employee.profile.date_birth
          - if controller_name == 'employees'
            td= render partial: 'block_btn', locals: {employee: employee}

app/views/employees/_list_departments.html.slim
- if departments
  #department-container
    - deps_id_employee = employee.departments.map(&:id)
    - departments.each do |department|
      - department_exists  = deps_id_employee.include?(department.id)
      .box.col-lg-3 data-id=department.id
        .btn class="#{department_exists ? 'btn-success active' : 'btn-default'}"
          h5= department.name
          - if policy(employee).related_to_department?
            - if department_exists
              = link_to related_to_department_employee_path(employee, connected: false, department_id: department.id), class: 'btn btn-default connect_to_department', id: 'disconnect_to_department', title: 'Disconnect department', data: {remote: true, connected: false} do
                i.fa.fa-minus-circle aria-hidden="true"
            - unless department_exists
              = link_to related_to_department_employee_path(employee, connected: true, department_id: department.id), class: 'btn btn-default connect_to_department', id: 'connect_to_department', title: 'Connect to Departments', data: {remote: true, connected: true} do
                i.fa.fa-plus-circle aria-hidden="true"

app/views/employees/_working_hours.html.slim
- working_hours = (employee.profile.working_hours || {})
- if working_hours.present?
  section.panel
    header.panel-heading
      i.fa.fa-clock-o &nbsp; Employee's Working Hours
    ul
      - Date::DAYNAMES.map(&:downcase).each do |week_day|
        - day = working_hours[week_day.to_sym]
        - if day
          li.agenda-days
            span.day= week_day.capitalize
            span.time.pull-right= "#{day[:from].in_time_zone} - #{day[:to].in_time_zone}"
            /span.time.pull-right= "#{day[:from].in_time_zone.strftime(t('time.formats.time'))} - #{day[:to].in_time_zone.strftime(t('time.formats.time'))}"
        - else
          li.agenda-days
            span.day= week_day.capitalize
            span.time.working-hours.pull-right Does not Work!

app/views/employees/destroy.js.slim
| $("table tr[data-id='#{@employee.id}']").remove()

app/views/employees/edit.html.slim
= render partial: 'form', locals: { employee: @employee,  action_path: employee_path(@employee) }

app/views/employees/index.html.slim
- if @department
  div class="row"
    h1
      span Department:
      span = @department.name
    .row
      .col-sm-6.col-lg-6.col-md-6
        - if policy(@department).connect_employees?
          = link_to connect_employees_department_path(@department), class: 'btn btn-primary btn-block connect_employees', data: {remote: true, id: @department.id} do
            i.fa.fa-users aria-hidden="true"
            em Connect employees
      .col-sm-6.col-lg-6.col-md-6
        = link_to new_department_employee_path(@department), class: 'btn btn-default btn-block' do
          i.fa.fa-plus
          span Create employee for Current department
  br
    = render partial: 'departments/employees'
div class='department-employees'
  - if policy(Employee).new?
    .pull-right
      = link_to new_employee_path, class: 'btn btn-default' do
        i.fa.fa-plus-circle aria-hidden="true"
        em Create Employee
  br
  - unless @employees.blank?
    .pull-right
      = will_paginate @employees
    div class="row"
      div class="col-sm-12 col-lg-12 col-md-12" id='department-employees'
        = render partial: 'lhs_table_users', locals: { employees: @employees }

    = render partial: 'employees/departments'

app/views/employees/new.html.slim
= render partial: 'form', locals: { employee: @employee, action_path: employees_path }

app/views/employees/related_to_department.js.slim
| $('#employee_info').html("#{escape_javascript(render partial: 'employees/info', locals: { employee: @employee } )}");
| $('#departments-ModalBody').html("#{escape_javascript(render partial: 'employees/list_departments', locals: { employee: @employee, departments: @departments } )}");
| $('[data-id="#{@employee.id}"]').find('.btn-circle').text("#{@employee.departments.count}");

app/views/employees/show.html.slim
div class="row"
  div class="col-sm-12 col-lg-12 col-md-12"
    /= debug @employee.profile.first_name
    /= debug @employee.profile.last_name
    /= debug @employee.profile.date_birth
    /= debug @employee.profile.gender
    = render partial: 'employees/block_btn', locals: { employee: @employee }
    br /
    span Employee:
    .row
      h3= @employee.profile.full_name
      span= @employee.email

      br /
      hr /
      span Profile:
      = @employee.profile.gender
      br /
      = @employee.profile.date_birth
      br /
      = @employee.departments.map(&:name)
    .row
      = render partial: 'employees/working_hours', object: @employee, as: :employee
/= render partial: 'departments/employees'