config/routes.rb
require 'versionist/routing_params.rb'

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :employees do
    member do
      match :related_to_department, to: 'employees#related_to_department', as: 'related_to_department', via: %i(get)
    end
  end

  resources :departments do
    member do
      match :connect_employee, to: 'departments#connect_employee', as: 'connect_employee', via: %i(get patch)
      match :connect_employees, via: %i(get post)
    end
  end
  # resources :users, only: %I[profile]

  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations' }


  ### API ###
  namespace :api, defaults: { format: :json } do
    api_version(api_version_params(1, defaults: { format: :json }, default: true)) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end

    end

    api_version(api_version_params(2, defaults: { format: :json })) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end
    end

  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :departments_employees
  has_and_belongs_to_many :employees, -> { distinct }, through: :departments_employees, dependent: :destroy

  validates :name, presence: true, length: { maximum: 64, minimum: 2 }
  validates :name, uniqueness: true

  scope :order_by_name, -> { order(name: :asc) }

  def count_of_employees
    employees.count
  end

  def pagination_links
    { first_page: '',
      next_page: '',
      prev_page: '',
      last_page: '' }
  end
end

app/controllers/api/departments_controller.rb
module Api
  class DepartmentsController < Api::BaseController
    before_action :load_departments, only: :index
    before_action :current_object, only: %i[show update destroy connected_employees connect_employees disconnect_employees]
    attr_accessor :departments
    before_action :authenticate_user!, except: %I[index]

    def default_serializer_options
      { serializer: namespace_for_serializer::DepartmentSerializer }
    end

    def index
      respond_with departments, meta: pagination_meta(departments).merge!(links: pagination_links(departments, sort: params[:sort])), adapter: :json
    end

    def show
      super
    end

    def create
      super
    end

    def update
      super
    end

    def destroy
      super
    end

    def connect_employees
      if department_params[:employee] && department_params[:employee].kind_of?(Array)
        Department.transaction do
          department_params[:employee].each do |employee|
            if employee[:email].present? && !employee[:email].blank?
              employee = Employee.find_by_email(employee[:email])
              next if DepartmentsEmployee.where(employee_id: employee.try(&:id)).present?
              current_object.employees << employee unless employee.nil?
            end
          end
        end
        respond_with current_object, status: :ok
      else
        respond_with current_object, status: :unprocessable_entity
      end
    end

    def disconnect_employees
      if department_params[:employee] && department_params[:employee].is_a?(Array)
        Department.transaction do
          department_params[:employee].each do |employee|
            if employee[:email].present? && !employee[:email].blank?
              employee = Employee.find_by_email(employee[:email])
              DepartmentsEmployee.where(employee_id: employee.id, department_id: current_object.id).delete_all
            end
          end
        end
        respond_with current_object, status: :ok
      else
        respond_with current_object, status: :unprocessable_entity
      end
    end

    def order_by(order_by)
      super
      if order_by && order_by.blank? || order_by.nil? || order_by == '-'
        'name'
      else
        order_by[0] == '-' ? order_by[1..-1] : order_by
      end
    end

    private

    def load_departments
      @departments ||= Department
                         .paginate(page: params[:page], per_page: Api::BaseController::PER_PAGE)
                         .order(sort_params(params[:sort]))
    end

    def department_params
      params.require(:department).permit(:id, :name, :description, employee: [:id, :email, :first_name, :last_name])
    end

    protected

    def pagination_links(data_object, sort:)
      {
        current_page: '',
        first_page: '',
        next_page: '',
        prev_page: '',
        last_page: ''
      }
    end
  end
end

app/controllers/api/v1/departments_controller.rb
module Api
  module V1
    class DepartmentsController < Api::DepartmentsController
      def pagination_links(data_object, sort:)
        super
        list = {}
        list[:current_page] = api_v1_departments_url(page: data_object.current_page, sort: sort)
        list[:first_page] = api_v1_departments_url(page: 1, sort: sort) unless data_object.current_page == 1
        list[:prev_page] = api_v1_departments_url(page: data_object.previous_page, sort: sort) unless data_object.previous_page.nil?
        list[:next_page] = api_v1_departments_url(page: data_object.next_page, sort: sort) unless data_object.next_page.nil?
        list[:last_page] = api_v1_departments_url(page: data_object.total_pages, sort: sort) unless data_object.total_pages == data_object.next_page
        list
      end
    end
  end
end

app/controllers/api/v2/departments_controller.rb
module Api
  module V2
    class DepartmentsController < Api::DepartmentsController
      def pagination_links(data_object, sort:)
        super
        list = {}
        list[:current_page] = api_v2_departments_url(page: data_object.current_page, sort: sort)
        list[:prev_page] = api_v2_departments_url(page: data_object.previous_page, sort: sort) unless data_object.previous_page.nil?
        list[:next_page] = api_v2_departments_url(page: data_object.next_page, sort: sort) unless data_object.next_page.nil?
        list
      end
    end
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!, except: %I[index]
  before_action :departments
  before_action :department, only: %i[show update edit destroy connect_employee connect_employees]
  respond_to :html, :json, :js

  attr_reader :departments, :department

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path, notice: 'Department create!'
    else
      render :new
    end
  end

  def update
    if department.update(department_params)
      redirect_to department_path(department), notice: 'Department successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    department.destroy
    respond_to do |format|
      format.html { redirect_to departments_path, notice: 'Department was successfully destroyed.' }
      format.js
    end
  end

  def connect_employees
    @employees ||= @department.employees
  end

  def connect_employee
    DepartmentsEmployee.where(department_id: department.id).delete_all
    manipulation_employees params[:department][:employees]
    department_employees
  end

  private

  def departments
    @departments ||= Department.order_by_name.paginate(page: params[:page], per_page: ApplicationController::PER_PAGE)
  end

  def department_employees
    @employees ||= department.employees
  end

  def department_params
    params.require(:department).permit :id, :name, :description
  end

  def department
    @department ||= Department.find params[:id]
  end

  def manipulation_employees(employees)
    return if employees.nil?
    employees = employees.reject! { |t| t == '' }
    employees.each do |email|
      @department.employees << Employee.where(email: email)
    end
  end
end

app/views/departments/_block_btn.html.slim
.pull-right
  - if policy(department).connect_employees?
    = link_to connect_employees_department_path(department), class: 'btn btn-default connect_employees', data: { remote: true, id: department.id } do
      i.fa.fa-users aria-hidden="true"
      em Employees
      em class="btn btn-circle btn-info" id="count_employees" = department.count_of_employees
  - if policy(department).update?
    = link_to edit_department_path(department), class: 'btn btn-primary' do
      i.fa.fa-pencil aria-hidden="true"
  - if policy(department).destroy?
    = link_to department_path(department), class: 'btn btn-danger', method: :delete, data: {remote: action_name == 'show' ? false : true, confirm: 'Are you sure?'} do
      i.fa.fa-trash aria-hidden="true"
  /- if policy(department).connect_to_department?
    = link_to connect_employee_department_path(department, current_user), class: 'btn btn-default', data: { remote: true } do
      i.fa.fa-user-plus aria-hidden="true"
      em Connect to department

app/views/departments/_employees.html.slim
.modal.fade id="employeeesModal" aria-hidden="true" aria-labelledby="employeeesModal" role="dialog"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" ×
        h4.modal-title#employees_title
          = "Employees:"
      .modal-body
        #employees-ModalBody

app/views/departments/_form.html.slim
.panel-body
  = form_for department, url: action_path, class: 'form-horizontal', role: 'form' do |f|
    .form-group.field class="#{department.errors.include?(:name) ? 'has-error' : ''}"
      = f.label :name, 'Department name *'
      = f.text_field :name, class: 'form-control'
      - if department.errors.include? :name
        span.help-block
          = error_message_for :name, department
    .form-group.field class="#{department.errors.include?(:description) ? 'has-error' : ''}"
      = f.label :description
      = f.text_area :description, class: 'form-control'
      - if department.errors.include? :description
        span.help-block
          = error_message_for :description, department
    .form-group
      = f.submit action_name == 'edit' ? 'Update' : 'Create', class: 'form-control btn btn-primary submit-button'

app/views/departments/_form_add_employees.html.slim
.panel-body
  = form_for department, url: connect_employee_department_path(department), data: { remote: true }, html: {class: 'form-horizontal', role: 'form', multipart: true} do |f|
    .form-group.field class="#{department.errors.include?(:employees) ? 'has-error' : ''}"
      = f.label :employees
      - employee_delected = department.employees.map{|c| c.email} || params[:department].try(:[], :employees)
      = f.select :employees, options_from_collection_for_select(Employee.eager_load(:profile), :email, :email, { selected: employee_delected} ), {}, {id: 'employees-select', class: 'form-control', multiple: true, style: 'width: 75%'}
    .form-group
      = f.submit 'Connect these Employees', class: 'form-control btn btn-primary submit-button'

javascript:
  $(document).ready(function(){
    $('#employees-select').select2({
      tags: 'true',
      tokenSeparators: [',', ' '],
      allowClear: true
    });
  })

app/views/departments/_lhs_table_departments.html.slim
.pull-right
  = will_paginate departments
table class="table table-hover table-inbox"
  tr
    th Name
    th Description
    th
    - departments.each do |department|
      tr data-id=department.id
        td
          div class="fa-hover col-md-3 col-sm-3"
            = link_to department_path(department), class: 'btn btn-default btn-sm' do
              = department.name
        td
          = department.description
        td
          = render partial: 'block_btn', locals: { department: department }

app/views/departments/_list_employees.html.slim
- if employees.empty?
  h4 You do not have any employees connected to this department.
  br
  | You Can Connect employee
  = render partial: 'departments/form_add_employees', locals: {department: department }
- else
  = render partial: 'departments/form_add_employees', locals: {department: department }
  = render partial: 'employees/lhs_table_users', locals: { employees: employees }

app/views/departments/connect_employee.js.slim
| $('#employeeesModal').modal('hide');
| $('#department-employees').html("#{escape_javascript(render partial: 'employees/lhs_table_users', locals: { employees: @employees, department: @department } )}");
| $('[data-id="#{@department.id}"]').find('.btn-circle').text("#{@department.count_of_employees}");

app/views/departments/connect_employees.js.slim
| $('#employees-ModalBody').html("#{escape_javascript(render partial: 'departments/list_employees', locals: { employees: @employees, department: @department } )}")

app/views/departments/destroy.js.slim
| $("table tr[data-id='#{@department.id}']").remove()

app/views/departments/edit.html.slim
= render partial: 'form', locals: { department: @department,  action_path: department_path(@department) }

app/views/departments/index.html.slim
- if policy(Department).new?
  div class="row"
    div class="col-lg-12 col-md-12"
      = link_to new_department_path, class: 'btn btn-default btn-block btn-bigg' do
        i class="fa fa-plus-square-o fa-2x pull-left"
        span Add Department
br
br
div class="row"
  div class="col-sm-12 col-lg-12 col-md-12"
    - unless @departments.blank?
      = render partial: 'lhs_table_departments', locals: { departments: @departments }

  = render partial: 'departments/employees'

app/views/departments/new.html.slim
= render partial: 'form', locals: { department: @department, action_path: departments_path }

app/views/departments/show.html.slim
div class="row"
  div class="col-sm-12 col-lg-12 col-md-12"
    = render partial: 'departments/block_btn', locals: { department: @department }
    br /
    span Name:
    h3
      = @department.name
    br /
    span Description:
    div
      = @department.description

= render partial: 'departments/employees'