config/routes.rb
require 'versionist/routing_params.rb'

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :employees do
    member do
      match :related_to_department, to: 'employees#related_to_department', as: 'related_to_department', via: %i(get)
    end
  end

  resources :departments do
    member do
      match :connect_employee, to: 'departments#connect_employee', as: 'connect_employee', via: %i(get patch)
      match :connect_employees, via: %i(get post)
    end
  end
  # resources :users, only: %I[profile]

  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations' }


  ### API ###
  namespace :api, defaults: { format: :json } do
    api_version(api_version_params(1, defaults: { format: :json }, default: true)) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end

    end

    api_version(api_version_params(2, defaults: { format: :json })) do
      resources :departments, only: %i(index show create update destroy) do
        member do
          match :connect_employees, to: 'departments#connect_employees', via: %i(post)
          match :disconnect_employees, to: 'departments#disconnect_employees', via: %i(post)
        end
      end
      resources :employees, only: %i(index show create update destroy)
      resources :sessions, only: %i(create destroy) do
        collection do
          match :current, to: 'sessions#current', via: %i(get)
        end
      end
    end

  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title HR-CRM
    meta name="keywords" content="template language"
    meta name="author" content='author'
    == stylesheet_link_tag    :application, media: :all, data: { turbolinks: { track: true } }
    == csrf_meta_tags
  body class="swag-line template-index"
    nav class="navbar navbar-landing navbar-inverse navbar-fixed-top" role='navigation'
      div class="container-fluid"
        div class="navbar-header"
          button class="navbar-toggle collapsed" type="button" data-target=".navbar-collapse" data-toggle="collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          = link_to 'HR-CRM', root_path
        div class="collapse navbar-collapse"
          ul class="nav navbar-nav navbar-left"
            li class="#{controller_name == 'departments' ? 'active' : ''}"
              = link_to 'Departments', departments_path
            li class="#{controller_name == 'employees' ? 'active' : ''}"
              = link_to 'Employes', employees_path
          = render 'shared/nav_user_links'
    div class="container-overflow-wrap"
      div class="container"
        = render 'shared/flash_messages'
        == yield
    div id="footer"
  = javascript_include_tag :application, media: :all, data: { turbolinks: { track: true } }
  = yield :javascript